services:
  app: 
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app

  db: 
    image: mysql:latest
    platform: linux/arm64
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest
    ports:
      - 3306:3306
    # volumes:
    #   - ./.docker/dbdata:/var/lib/mysql
      